### ISSUE TITLE
Upgrade to PHP 7.2

### ISSUE THREAD

**Issue by Lynngre** [akvo/akvo-web#1286]
Reason: improve speed & performance, ensure running supported version.
To do: Test incompatibilities.

**Comment by samvthom16** [comment]
The json data plugin that is on the See It Happen page, which pulls all the RSR feeds, needs to be updated for the latest version. 

@Lindaleunissen and @ajdesalvo have confirmed that we are going to remove the See It Happen page.

**Comment by samvthom16** [comment]
/home/sites/public_html/wp-content/themes/Akvo-responsive/inc/widgets/testimonial-widget.php
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
3 | WARNING | Function create_function() is deprecated since PHP 7.2; Use an anonymous function instead

Unnecessary & unused widgets have been removed here https://github.com/akvo/akvo-web/commit/7123f5107aefb870b16e5a71750d5e40563ce4e5

**Comment by Lynngre** [comment]
Site has been updated.
