### ISSUE TITLE
Overlapping map pins on Contact us page

### ISSUE THREAD

**Issue by JoPratt** [akvo/akvo-web#626]
The Bamako map pin overlaps and hides the Ouagadougou one. Is it possible to make (one of) the pins point sideways to avoid each other?

**Comment by gabemart** [comment]
@JoPratt Yep! I will fix this today with a little css

**Comment by Lynngre** [comment]
Still an issue.  BKO overlapping Mali.

**Comment by gabemart** [comment]
@Lynngre it turns out this was a front-end issue. Akvo.org was lacking the correct custom fields for changes that were made to the code to fix this issue.

I've fixed it now. There is now a checkbox in the backend that, when checked, flips the relevant pin upside-down - so if we add more pins in the future and more need to be flipped, we can do so without any code changes.

http://akvo.org/contact-info/
