### ISSUE TITLE
Simple Tooltips plugin broken

### ISSUE THREAD

**Issue by zzgvh** [akvo/akvo-web#634]
The WP plugin Simple Tooltips is currently broken. I don't know the root cause but the result is that there's a javascript error on every page that prevents other (following) scripts to run properly. @gabemart helped me trace it back the the Simple Tooltips plugin.

In FireFox dev tools when visiting [akvo.org](http://akvo.org):

![screenshot_83](https://cloud.githubusercontent.com/assets/142613/7881978/2bd0a6e4-0609-11e5-8e14-ad687e98c5e0.png)

So I'm disabling this locally for my development of RSR KPI charts, but the question remains where tooltips are used on the site. I've found **tooltips** classes on the networkPage, so I'm guessing that's one place.

Do we want to try fix this, or should we ditch the plugin?

**Comment by gabemart** [comment]
I have looked into why the plugin isn't working, but the problem is not obvious to me. For some reason, Zebra_Tooltips is not being attached to the jQuery object (jQuery.Zebra_Tooltips is undefined). The script is being injected properly (/wp-content/plugins/simple-tooltips/zebra_tooltips.js?ver=4.2.1) and I can't see why it's not working.

Spoke briefly with @loicsans about this, we agreed we should find another plugin

**Comment by Lynngre** [comment]
@gabemart @loicsans any further progress on this issue?

**Comment by Lynngre** [comment]
@gabemart could you check https://github.com/jaz303/tipsy ?

**Comment by Lynngre** [comment]
This issue also causes the tooltips on the seeithappen page not to function as well as the popup windows on the partner, organisations & team page.

**Comment by loicsans** [comment]
I am coding a custom solution for us.
